### ISSUE TITLE
Does this actor not extract from input URLs? 

### ISSUE THREAD

**Issue by SeanBannister** [metalwarrior665/actor-article-extractor-smart#2]
Thanks for this actor. I think I've realised this actor only scrapes articles on pages that it crawls to and not the first page that the user provides as input. Could you confirm this?

In my case I'm looking to provide a list of URLs and not crawl any deeper. My settings currently look like:

![image](https://user-images.githubusercontent.com/197231/83101481-c6258200-a0f5-11ea-843d-7389f752bfc1.png)

**Comment by metalwarrior665** [comment]
Hello,

Thanks for the feedback. You should be able to achieve this by passing `userData` with each request like this:

```
{
     "label": "ARTICLE"     
}
```

Then the start URL will be scraped as an article. Otherwise, it is taken as category and it is enqueuing more.

It is not properly documented so good motivation to finally end the documentation.

**Comment by SeanBannister** [comment]
Thanks a heap that was exactly what I was looking for. 

Thought you might find my use case interesting, I'm using [google-search-scraper](https://apify.com/apify/google-search-scraper) to grab the URLs from search results and then parsing them to smart article extractor. Currently this requires a bit of a hack to achieve but I'm currently [trying to work out a better way of doing it](https://github.com/apifytech/apify-js/issues/707).

**Comment by metalwarrior665** [comment]
That's cool! Yeah, obviously our focus mainly on the Apify platform integration but this feature is something that we should eventually have. Thanks for pointing that out!
