### ISSUE TITLE
Parsed date: points to wrong data

### ISSUE THREAD

**Issue by pocesar** [metalwarrior665/actor-article-extractor-smart#5]
confuses users seeing: `2020-09-21T00:56:39.543Z Parsed date: null` but the `parsedDate` is actually being output

https://github.com/metalwarrior665/actor-article-extractor-smart/blob/ab61ad1eddeb45e1f82b0ef2412b3a24d6964ae0/src/main.js#L326

**Comment by metalwarrior665** [comment]
Thanks, fixed
