### ISSUE TITLE
Not being able to detect date with Must have Date turned on

### ISSUE THREAD

**Issue by pocesar** [metalwarrior665/actor-article-extractor-smart#6]
Example url: https://www.clozette.co/article/trending-footwear-designs-team-clozette-7408

Gives: `2020-09-28T00:15:52.531Z IS NOT VALID ARTICLE --- date: false, title: true, words: 858, dateRange: false --- https://www.clozette.co/article/trending-footwear-designs-team-clozette-7408`

if possible, date parsed from extended output should also be considered when validating the date of the page, anything that have `date` in the name, like `datePublished`

**Comment by metalwarrior665** [comment]
This can already be done by overwriting the original `date` field which is what is checked. I added a new feature that `currentItem` is passed into the  `extendOutputFunction` so you can keep the originalDate for reference.

```
($, currentItem) => {
    return {
        date: $('.correct-date-selector').text().trim(),
        originalDate: currentItem.date,
    }
}
```
